version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1232
      POSTGRES_DB: trusttrack
    networks:
      - tt
networks:
  tt:
